int Streamer_TickRate(int rate);
int Streamer_MaxItems(int type, int items);
int Streamer_VisibleItems(int type, int items);
int Streamer_CellDistance(float distance);
int Streamer_CellSize(float size);
int Streamer_ProcessActiveItems();
int Streamer_ToggleIdleUpdate(int playerid, int toggle);
int Streamer_ToggleItemUpdate(int playerid, int type, int toggle);
int Streamer_Update(int playerid);
int Streamer_UpdateEx(int playerid, float x, float y, float z, int worldid, int interiorid);
int Streamer_GetFloatData(int type, int id, int data, float& result);
int Streamer_SetFloatData(int type, int id, int data, float value);
int Streamer_GetIntData(int type, int id, int data);
int Streamer_SetIntData(int type, int id, int data, int value);
int Streamer_SetArrayData(int type, int id, int data, int* src, int maxlength);
int Streamer_IsInArrayData(int type, int id, int data, int value);
int Streamer_AppendArrayData(int type, int id, int data, int value);
int Streamer_RemoveArrayData(int type, int id, int data, int value);
int Streamer_GetUpperBound(int type);
int Streamer_GetDistanceToItem(float x, float y, float z, int type, int id, float& distance);
int Streamer_IsItemVisible(int playerid, int type, int id);
int Streamer_DestroyAllVisibleItems(int playerid, int type);
int Streamer_CountVisibleItems(int playerid, int type);
int CreateDynamicObject(int modelid, float x, float y, float z, float rx, float ry, float rz, int worldid, int interiorid, int playerid, float streamdistance);
int DestroyDynamicObject(int objectid);
int IsValidDynamicObject(int objectid);
int SetDynamicObjectPos(int objectid, float x, float y, float z);
int GetDynamicObjectPos(int objectid, float& x, float& y, float& z);
int SetDynamicObjectRot(int objectid, float rx, float ry, float rz);
int GetDynamicObjectRot(int objectid, float& rx, float& ry, float& rz);
int MoveDynamicObject(int objectid, float x, float y, float z, float speed, float rx, float ry, float rz);
int StopDynamicObject(int objectid);
int IsDynamicObjectMoving(int objectid);
int AttachCameraToDynamicObject(int playerid, int objectid);
int AttachDynamicObjectToVehicle(int objectid, int vehicleid, float offsetx, float offsety, float offsetz, float rx, float ry, float rz);
int EditDynamicObject(int playerid, int objectid);
int GetDynamicObjectMaterial(int objectid, int materialindex, int& modelid, int* txdname, int* texturename, int& materialcolor, int maxtxdname, int maxtexturename);
int SetDynamicObjectMaterial(int objectid, int materialindex, int modelid, int* txdname, int* texturename, int materialcolor);
int GetDynamicObjectMaterialText(int objectid, int materialindex, int* text, int& materialsize, int* fontface, int& fontsize, int& bold, int& fontcolor, int& backcolor, int& textalignment, int maxtext, int maxfontface);
int SetDynamicObjectMaterialText(int objectid, int materialindex, int* text, int materialsize, int* fontface, int fontsize, int bold, int fontcolor, int backcolor, int textalignment);
int DestroyAllDynamicObjects();
int CountDynamicObjects();
int CreateDynamicPickup(int modelid, int type, float x, float y, float z, int worldid, int interiorid, int playerid, float streamdistance);
int DestroyDynamicPickup(int pickupid);
int IsValidDynamicPickup(int pickupid);
int DestroyAllDynamicPickups();
int CountDynamicPickups();
int CreateDynamicCP(float x, float y, float z, float size, int worldid, int interiorid, int playerid, float streamdistance);
int DestroyDynamicCP(int checkpointid);
int IsValidDynamicCP(int checkpointid);
int TogglePlayerDynamicCP(int playerid, int checkpointid, int toggle);
int TogglePlayerAllDynamicCPs(int playerid, int toggle);
int IsPlayerInDynamicCP(int playerid, int checkpointid);
int GetPlayerVisibleDynamicCP(int playerid);
int DestroyAllDynamicCPs();
int CountDynamicCPs();
int CreateDynamicRaceCP(int type, float x, float y, float z, float nextx, float nexty, float nextz, float size, int worldid, int interiorid, int playerid, float streamdistance);
int DestroyDynamicRaceCP(int checkpointid);
int IsValidDynamicRaceCP(int checkpointid);
int TogglePlayerDynamicRaceCP(int playerid, int checkpointid, int toggle);
int TogglePlayerAllDynamicRaceCPs(int playerid, int toggle);
int IsPlayerInDynamicRaceCP(int playerid, int checkpointid);
int GetPlayerVisibleDynamicRaceCP(int playerid);
int DestroyAllDynamicRaceCPs();
int CountDynamicRaceCPs();
int CreateDynamicMapIcon(float x, float y, float z, int type, int color, int worldid, int interiorid, int playerid, float streamdistance);
int DestroyDynamicMapIcon(int iconid);
int IsValidDynamicMapIcon(int iconid);
int DestroyAllDynamicMapIcons();
int CountDynamicMapIcons();
int CreateDynamic3DTextLabel(int* text, int color, float x, float y, float z, float drawdistance, int attachedplayer, int attachedvehicle, int testlos, int worldid, int interiorid, int playerid, float streamdistance);
int DestroyDynamic3DTextLabel(int id);
int IsValidDynamic3DTextLabel(int id);
int GetDynamic3DTextLabelText(int id, int* text, int maxlength);
int UpdateDynamic3DTextLabelText(int id, int color, int* text);
int DestroyAllDynamic3DTextLabels();
int CountDynamic3DTextLabels();
int CreateDynamicCircle(float x, float y, float size, int worldid, int interiorid, int playerid);
int CreateDynamicRectangle(float minx, float miny, float maxx, float maxy, int worldid, int interiorid, int playerid);
int CreateDynamicSphere(float x, float y, float z, float size, int worldid, int interiorid, int playerid);
int CreateDynamicCube(float minx, float miny, float minz, float maxx, float maxy, float maxz, int worldid, int interiorid, int playerid);
int CreateDynamicPolygon(float* points, float minz, float maxz, int maxpoints, int worldid, int interiorid, int playerid);
int DestroyDynamicArea(int areaid);
int IsValidDynamicArea(int areaid);
int TogglePlayerDynamicArea(int playerid, int areaid, int toggle);
int TogglePlayerAllDynamicAreas(int playerid, int toggle);
int IsPlayerInDynamicArea(int playerid, int areaid);
int IsPlayerInAnyDynamicArea(int playerid);
int IsPointInDynamicArea(int areaid, float x, float y, float z);
int IsPointInAnyDynamicArea(float x, float y, float z);
int AttachDynamicAreaToObject(int areaid, int objectid, int type, int playerid);
int AttachDynamicAreaToPlayer(int areaid, int playerid);
int AttachDynamicAreaToVehicle(int areaid, int vehicleid);
int DestroyAllDynamicAreas();
int CountDynamicAreas();
int CreateDynamicObjectEx(int modelid, float x, float y, float z, float rx, float ry, float rz, float drawdistance, float streamdistance, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicPickupEx(int modelid, int type, float x, float y, float z, float streamdistance, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicCPEx(float x, float y, float z, float size, float streamdistance, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicRaceCPEx(int type, float x, float y, float z, float nextx, float nexty, float nextz, float size, float streamdistance, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicMapIconEx(float x, float y, float z, int type, int color, int style, float streamdistance, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamic3DTextLabelEx(int* text, int color, float x, float y, float z, float drawdistance, int attachedplayer, int attachedvehicle, int testlos, float streamdistance, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicCircleEx(float x, float y, float size, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicRectangleEx(float minx, float miny, float maxx, float maxy, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicSphereEx(float x, float y, float z, float size, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicCubeEx(float minx, float miny, float minz, float maxx, float maxy, float maxz, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
int CreateDynamicPolygonEx(float* points, float minz, float maxz, int maxpoints, int* worlds, int* interiors, int* players, int maxworlds, int maxinteriors, int maxplayers);
